export const UPDATE_SEARCH_VALUE   = 'UPDATE_SEARCH_VALUE';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const CLEAR_SEARCH_RESULTS  = 'CLEAR_SEARCH_RESULTS';
export const UPDATE_LOADING        = 'UPDATE_LOADING';
